// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFcYAz9NpB5i8VgbGoOCH2yitjYO2IiWo',
    appId: '1:812237587762:web:227947c3f05331eb95832b',
    messagingSenderId: '812237587762',
    projectId: 'app-historial-vehiculo',
    authDomain: 'app-historial-vehiculo.firebaseapp.com',
    storageBucket: 'app-historial-vehiculo.firebasestorage.app',
    measurementId: 'G-8SHQ375FB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJueDwsH3oY5OZqIREj0nlW0nI6qaiB4Y',
    appId: '1:812237587762:android:7d985a87b6186ecb95832b',
    messagingSenderId: '812237587762',
    projectId: 'app-historial-vehiculo',
    storageBucket: 'app-historial-vehiculo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSilhALxAPcAo6t5d76_-97K3sB1AU4II',
    appId: '1:812237587762:ios:49c87bcf336976bc95832b',
    messagingSenderId: '812237587762',
    projectId: 'app-historial-vehiculo',
    storageBucket: 'app-historial-vehiculo.firebasestorage.app',
    iosBundleId: 'com.example.appHistorialVehiculo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSilhALxAPcAo6t5d76_-97K3sB1AU4II',
    appId: '1:812237587762:ios:49c87bcf336976bc95832b',
    messagingSenderId: '812237587762',
    projectId: 'app-historial-vehiculo',
    storageBucket: 'app-historial-vehiculo.firebasestorage.app',
    iosBundleId: 'com.example.appHistorialVehiculo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFcYAz9NpB5i8VgbGoOCH2yitjYO2IiWo',
    appId: '1:812237587762:web:550df0d174c256f695832b',
    messagingSenderId: '812237587762',
    projectId: 'app-historial-vehiculo',
    authDomain: 'app-historial-vehiculo.firebaseapp.com',
    storageBucket: 'app-historial-vehiculo.firebasestorage.app',
    measurementId: 'G-1XE1E3CTSG',
  );
}
